### ISSUE TITLE
Wrong classname imported in resources.js

### ISSUE THREAD

**Issue by mmilitzer** [tliron/prudence#31]
Hi Tal,

I just noticed an issue with l. 936 of resources.js:

https://github.com/tliron/prudence/blob/8262b13db182f9f7ac365eb4eed8faeea77dc502/components/prudence-javascript-library/libraries/scripturian/prudence/resources.js#L936

At least with my restlet version (2.3.4) the importClass() fails. Reason is that the actual class name is "org.restlet.data.Header" and not "org.restlet.data.header.Header". After changing it, things seem to work ok.

**Comment by tliron** [comment]
Fixed, thanks!
